### PR TITLE
Only update changelog when response has it

### PR DESCRIPTION
**Pull request by cklosowski**
Not sure exactly why, but I kept getting a JS error when trying to Fetch stating that couldn't 'setContent' with an item that didn't exist. Just wrapping the setContent with a check to see if the response contains the `changelog` item first.

### CODE REVIEW

**Comment by kstover** [comment]
Good catch @cklosowski. Whenever you guys want me to release an update, let me know. For future PRs, make sure to assign me so that I get pinged. :)

**Comment by cklosowski** [comment]
@kstover Go ahead and get it into a release as soon as you can, and we'll push a minor update for users.

**Comment by pippinsplugins** [comment]
@kstover Any chance of getting this tagged for release?

**Comment by kstover** [comment]
Updated to version 1.0.1.

**Pull request merged**
